# Generated by Django 5.1.3 on 2025-03-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('housing', models.FloatField()),
                ('food', models.FloatField()),
                ('transport', models.FloatField()),
                ('other', models.FloatField()),
            ],
        ),
    ]
